title: PSIN Lab
description: Le blog des projets numeriques des groupes PSIN Astrolabe et Gidef.
logo: /assets/images/astrolabe/logo3.png
url: "https://psin.epie-formation.net"
baseurl: ""
lang: fr
timezone: Europe/Paris

permalink: /:categories/:year/:month/:day/:title/

author:
  name: Laurent

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

collections:
  glossaire:
    output: true
    permalink: /glossaire/:name/

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: glossaire
    values:
      layout: glossary-term

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
