title: PSIN Lab
description: Le blog des projets numeriques des groupes PSIN Astrolabe et Gidef.
url: "https://epie.laurents.fr"
baseurl: ""
lang: fr
timezone: Europe/Paris

permalink: /:categories/:year/:month/:day/:title/

author:
  name: Laurent

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
